---

# == Notes ==

# - GitLab automatically passes artifacts from previous stages by default
# - Set required secret variables at: https://gitlab.data.bas.ac.uk/web-apps/flask-middleware/flask-azure-oauth/settings/ci_cd

# = Secret variables
# - Variables are grouped by section in KEY: "value" format (e.g. FOO: "bar")
#   Sensitive values are represented by "[Sensitive]"
#
# - Snyk
# > SNYK_TOKEN: "[Sensitive]"
#
# - PyPi (production)
# > PYPI_PASSWORD: "[Sensitive]"
#
# - PyPi (staging)
# > PYPI_TEST_PASSWORD: "[Sensitive]"

# == Global settings ==

stages:
  - test
  - lint
  - build
  - publish

variables:
  APP_NAME: flask-azure-oauth
  SNYK_ORG: antarctica
  SNYK_PROJECT: flask-middleware-azure-oauth
  PYPI_USERNAME: british-antarctic-survey
  PYPI_TEST_USERNAME: british-antarctic-survey

image:
  name: docker-registry.data.bas.ac.uk/web-apps/flask-middleware/flask-azure-oauth:0.1.0-alpine
  entrypoint: [""]

# == Jobs ==

test-app:
  stage: test
  variables:
    FLASK_ENV: testing
  script:
    - "flask test"

dependencies-app:
  stage: lint
  image:
    name: antarctica/snyk-cli:python-3
    entrypoint: [""]
  script:
   - "pip install -r requirements.txt"
   - "snyk test"
   - "snyk monitor --project-name=$SNYK_PROJECT --org=$SNYK_ORG"
  only:
    - master

pep8-app:
  stage: lint
  script:
    - "flake8 . --ignore=E501"

bandit-app:
  stage: lint
  script:
    - "bandit -r ."

build-app:
  stage: build
  script:
    - "python setup.py sdist bdist_wheel"
  artifacts:
    name: "$CI_BUILD_TOKEN-build"
    paths:
      - dist
    expire_in: 1 month

publish-app-stage:
  stage: publish
  script:
    - "python -m twine upload --repository-url https://test.pypi.org/legacy/ --username $PYPI_TEST_USERNAME --password $PYPI_TEST_PASSWORD --disable-progress-bar --verbose dist/*"
  only:
    - master
  environment:
    name: staging
    url: https://test.pypi.org/project/flask-azure-oauth/

publish-app-prod:
  stage: publish
  script:
    - "python -m twine upload --username $PYPI_USERNAME --password $PYPI_PASSWORD --disable-progress-bar --verbose dist/*"
  only:
    - tags
  environment:
    name: production
    url: https://pypi.org/project/flask-azure-oauth/
