---
version: "2"

services:
  app:
    build: .
    image: docker-registry.data.bas.ac.uk/web-apps/flask-middleware/flask-azure-oauth:0.1.0-alpine
    command: flask run --host 0.0.0.0 --port 9000
    volumes:
      - .:/usr/src/app
    ports:
      - 9000:9000
