[tool.poetry]
name = "flask-azure-oauth"
version = "0.0.0"
license = "MIT"
description = "Python Flask extension for using Azure Active Directory with OAuth to protect applications"
authors = [
    "Felix Fennell <felnne@bas.ac.uk>"
]
readme = "README.md"
homepage = "https://github.com/antarctica/flask-azure-oauth"
repository = "https://github.com/antarctica/flask-azure-oauth"
classifiers = [
    "Programming Language :: Python :: 3",
    "Framework :: Flask",
    "Development Status :: 5 - Production/Stable",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers"
]

[tool.poetry.dependencies]
authlib = "0.14.3"  # pinned due to https://github.com/lepture/authlib/issues/314#issuecomment-773132848
Flask = "^2.0.2"
requests = "^2.23.0"
python = "^3.6"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.3"
flake8-bugbear = "^22.1.11"
flake8-builtins = "^1.5.3"
flake8-import-order = "^0.18.1"
flake8-use-fstring = "^1.3"
msal = "^1.4.1"
safety = "^1.10.3"
tomlkit = "^0.8.0"
unittest-xml-reporting = "^3.0.2"

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = ''

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
